### PR TITLE
Service improvements

### PR DESCRIPTION
**Pull request by netson**
Hi, first of all, thanks for creating this module! :) Saved me a bunch of time when integrating psad into my puppet agents.

However, I ran into some issues on Ubuntu (14.04 Server LTS) when requiring a restart of the psad service.

For example, when I manually shut down the psad service, running the puppet agent did not automatically restart it.

Also, when PSAD is already running and a configuration file has changed, thus requiring a restart, puppet would not do this correctly because on my system it uses `/usr/sbin/psad restart`, which outputs the following `[*] /usr/sbin/psad process is already running! Exiting.` (exit code 1), and so your config changes are not activated.

Last but not least, the default `service psad status` or `psad -S` (identical) is not the correct way to determine if psad is running, and it can take a long time to perform on a system which has been running for a while and as a result, slows down your puppet run times. I changed this by checking to see if the psad process is running or not and using the exit code of the grep command to determine success or failure. This is much quicker and safer way to determine if PSAD is running or not. PSAD's behaviour, by the way, also causes Ubuntu to think it is not running, while in fact it is. Try a `service --status-all` for example, and then a `psad -S`, the first will tell you it is not running, the second will tell you it is.

Maybe these issues are only related to Ubuntu, I have only tested this on Ubuntu Server 12.04 & 14.04 LTS (64-bit).

The changes I made to the service class fixed the above issues for me so hopefully you will merge them back into your master! :+1:

### CODE REVIEW

**Comment by tedivm** [comment]
Awesome, thanks for the pull request!

**Comment by tedivm** [comment]
The newest version is up on puppet forge. Thanks again for your contribution!

**Comment by netson** [comment]
No problem! :)

I'm working on something else as well: installing via the downloadable tarball to circumvent the automatic dependency for postfix on Ubuntu systems. Once I get it working I'll create another pull request!

Regards,
Rinck

**Comment by tedivm** [comment]
Cool, I like that plan. Try to make it optional though for people who still want to use their package managers.

**Pull request merged**
